### ISSUE TITLE
Parameter specified as non-null is null

### ISSUE THREAD

**Issue by dimon4ezzz** [dimon4ezzz/cargo-transportation-modelling#2]
At random time the application prints to log this message:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method ru.edu.urfu.dimon4ezzz.cargo.comparators.PointComparator.compare, parameter o2
at ru.edu.urfu.dimon4ezzz.cargo.comparators.PointComparator.compare(PointComparator.kt)
	at ru.edu.urfu.dimon4ezzz.cargo.comparators.PointComparator.compare(PointComparator.kt:11)
	at java.base/java.util.PriorityQueue.siftDownUsingComparator(PriorityQueue.java:713)
	at java.base/java.util.PriorityQueue.poll(PriorityQueue.java:586)
	at ru.edu.urfu.dimon4ezzz.cargo.Router.getNextPointAndRecalculate(Router.kt:147)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck.move(Truck.kt:139)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck.access$move(Truck.kt:23)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck$defaultTruckActionListener$1.onComplete(Truck.kt:93)
	at ru.edu.urfu.dimon4ezzz.cargo.tasks.TruckTakingTask.run(TruckTakingTask.kt:17)
```

**Comment by dimon4ezzz** [comment]
same with parameter `o1`:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method ru.edu.urfu.dimon4ezzz.cargo.comparators.PointComparator.compare, parameter o1
	at ru.edu.urfu.dimon4ezzz.cargo.comparators.PointComparator.compare(PointComparator.kt)
	at ru.edu.urfu.dimon4ezzz.cargo.comparators.PointComparator.compare(PointComparator.kt:11)
	at java.base/java.util.PriorityQueue.siftDownUsingComparator(PriorityQueue.java:713)
	at java.base/java.util.PriorityQueue.poll(PriorityQueue.java:586)
	at ru.edu.urfu.dimon4ezzz.cargo.Router.getNextPointAndRecalculate(Router.kt:147)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck.move(Truck.kt:139)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck.access$move(Truck.kt:23)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck$move$$inlined$let$lambda$1.onComplete(Truck.kt:168)
	at ru.edu.urfu.dimon4ezzz.cargo.tasks.TruckGivingTask.run(TruckGivingTask.kt:15)
```

**Comment by dimon4ezzz** [comment]
look at:
- https://github.com/dimon4ezzz/cargo-transportation-modeling/blob/07312e58947e692556b2d64c555bdfe8da10120c/src/main/kotlin/ru/edu/urfu/dimon4ezzz/cargo/models/Truck.kt#L93
- https://github.com/dimon4ezzz/cargo-transportation-modeling/blob/07312e58947e692556b2d64c555bdfe8da10120c/src/main/kotlin/ru/edu/urfu/dimon4ezzz/cargo/models/Truck.kt#L168

**Comment by dimon4ezzz** [comment]
i have try to represent it and found the cause: truck tries to remove point from queue **twice**
