### ISSUE TITLE
NullPointerException at Kotlin project! 😲

### ISSUE THREAD

**Issue by dimon4ezzz** [dimon4ezzz/cargo-transportation-modelling#3]
At random time the application prints to log this:
```
java.lang.NullPointerException
	at java.base/java.util.PriorityQueue.offer(PriorityQueue.java:326)
	at java.base/java.util.PriorityQueue.add(PriorityQueue.java:312)
	at ru.edu.urfu.dimon4ezzz.cargo.Router.initPath(Router.kt:208)
	at ru.edu.urfu.dimon4ezzz.cargo.Router.addOrder(Router.kt:63)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck$defaultOrderQueueListener$1.onPush(Truck.kt:55)
	at ru.edu.urfu.dimon4ezzz.cargo.Auction.doesAnybodyTakeThis(Auction.kt:83)
	at ru.edu.urfu.dimon4ezzz.cargo.Auction.removeOrderQueueListener(Auction.kt:72)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck$defaultTruckActionListener$1.onComplete(Truck.kt:89)
	at ru.edu.urfu.dimon4ezzz.cargo.tasks.TruckTakingTask.run(TruckTakingTask.kt:17)
```

**Comment by dimon4ezzz** [comment]
`NullPointerException` again:
```
java.lang.NullPointerException
	at java.base/java.util.PriorityQueue.offer(PriorityQueue.java:326)
	at java.base/java.util.PriorityQueue.add(PriorityQueue.java:312)
	at ru.edu.urfu.dimon4ezzz.cargo.Router.initPath(Router.kt:208)
	at ru.edu.urfu.dimon4ezzz.cargo.Router.addOrder(Router.kt:63)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck$defaultOrderQueueListener$1.onPush(Truck.kt:55)
	at ru.edu.urfu.dimon4ezzz.cargo.Auction$checkOrdersAndAskItLast$1.test(Auction.kt:96)
	at ru.edu.urfu.dimon4ezzz.cargo.Auction$checkOrdersAndAskItLast$1.test(Auction.kt:11)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.bulkRemove(ConcurrentLinkedQueue.java:1004)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.removeIf(ConcurrentLinkedQueue.java:964)
	at ru.edu.urfu.dimon4ezzz.cargo.Auction.checkOrdersAndAskItLast(Auction.kt:95)
	at ru.edu.urfu.dimon4ezzz.cargo.Auction.addOrderQueueListener(Auction.kt:49)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck.setListenerToLocationSource(Truck.kt:129)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck.move(Truck.kt:149)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck.access$move(Truck.kt:23)
	at ru.edu.urfu.dimon4ezzz.cargo.models.Truck$move$$inlined$let$lambda$1.onComplete(Truck.kt:168)
	at ru.edu.urfu.dimon4ezzz.cargo.tasks.TruckGivingTask.run(TruckGivingTask.kt:15)
```
